### ISSUE TITLE
Onvif soap fault

### ISSUE THREAD

**Issue by grolsch1986** [AdyRock/com.onvif#53]
Ik probeer een 2e camera toe te voegen via de app vind hij de camera wel automatisch en als ik probeer in te loggen krijg ik error onvif soap fault als melding.wat is hier aan de hand mvg marcel

**Comment by GuttormH** [comment]
I have the same problem, using two types of camera, this worked before, about a month ago..

**Comment by shurick1983** [comment]
I am also unable to connect my Hikvision camera to ONVIF.  The camera is detected during the search, but during authorization it gives an error.  Through the Home assistant, it connects without problems using also ONVIF.  What could be the problem?
![Screenshot_20230714_213936_Homey](https://github.com/AdyRock/com.onvif/assets/131009382/dc156bd1-7e82-4dc0-915c-f7fee9fc8880)

**Comment by AdyRock** [comment]
Could you open the Apps settings and set the Diagnostics log to Detailed Information, then try to add the camera and after it fails, go back to the settings page and send the log.

**Comment by shurick1983** [comment]
Hello,


I noticed that the time in the log is three hours less than it really is.

LOG:

xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12" xmlns:http="
http://schemas.xmlsoap.org/wsdl/http" xmlns:d="
http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsadis="
http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsnt="
http://docs.oasis-open.org/wsn/b-2" xmlns:wsa="
http://www.w3.org/2005/08/addressing" xmlns:wstop="
http://docs.oasis-open.org/wsn/t-1" xmlns:wsrf-bf="
http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsntw="
http://docs.oasis-open.org/wsn/bw-2" xmlns:wsrf-rw="
http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsaw="
http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsrf-r="
http://docs.oasis-open.org/wsrf/r-2" xmlns:trc="
http://www.onvif.org/ver10/recording/wsdl" xmlns:tse="
http://www.onvif.org/ver10/search/wsdl" xmlns:trp="
http://www.onvif.org/ver10/replay/wsdl" xmlns:tnshik="
http://www.hikvision.com/2011/event/topics" xmlns:hikwsd="
http://www.onvifext.com/onvif/ext/ver10/wsdl" xmlns:hikxsd="
http://www.onvifext.com/onvif/ext/ver10/schema" xmlns:tas="
http://www.onvif.org/ver10/advancedsecurity/wsdl" xmlns:tr2="
http://www.onvif.org/ver20/media/wsdl" xmlns:axt="
http://www.onvif.org/ver20/analytics"><env:Body><tr2:GetProfilesResponse><tr2:Profiles
token="Profile_1" fixed="true"><tr2:Name>mainStream</tr2:Name>
<tr2:Configurations></tr2:Configurations>
</tr2:Profiles>
<tr2:Profiles token="Profile_2" fixed="true"><tr2:Name>subStream</tr2:Name>
<tr2:Configurations></tr2:Configurations>
</tr2:Profiles>
</tr2:GetProfilesResponse>
</env:Body>
</env:Envelope>


19:10:38.238:
_request (192.168.1.37): {
"hostname": "192.168.1.37",
"port": 80,
"path": "/onvif/Media2",
"agent": false,
"timeout": 15000,
"headers": {
"Content-Type": "application/soap+xml; charset: utf-8; action=\"
http://www.onvif.org/ver10/media/wsdl/GetVideoSources\"",
"Content-Length": 1022,
"charset": "utf-8"
},
"method": "POST"
}
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="
http://www.w3.org/2005/08/addressing"><s:Header><a:MessageID>
urn:uuid:7754573f-bf55-5610-3f41-785d2a60971d</a:MessageID><Security
s:mustUnderstand="1" xmlns="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password
Type="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">a4s6f6Pswwexd6+w1heqPrMD8IE=</Password><Nonce
EncodingType="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">KbwlqaKl1+7ZpscrXMzl6A==</Nonce><Created
xmlns="
http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-07-14T19:10:38.133Z</Created></UsernameToken></Security></s:Header><s:Body
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="
http://www.w3.org/2001/XMLSchema"><GetVideoSources xmlns="
http://www.onvif.org/ver10/media/wsdl"/></s:Body></s:Envelope>

19:10:38.261:
_request response (192.168.1.37): <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope"
xmlns:soapenc="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="
http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="
http://www.w3.org/2001/XMLSchema" xmlns:tt="
http://www.onvif.org/ver10/schema" xmlns:tds="
http://www.onvif.org/ver10/device/wsdl" xmlns:trt="
http://www.onvif.org/ver10/media/wsdl" xmlns:timg="
http://www.onvif.org/ver20/imaging/wsdl" xmlns:tev="
http://www.onvif.org/ver10/events/wsdl" xmlns:tptz="
http://www.onvif.org/ver20/ptz/wsdl" xmlns:tan="
http://www.onvif.org/ver20/analytics/wsdl" xmlns:tst="
http://www.onvif.org/ver10/storage/wsdl" xmlns:ter="
http://www.onvif.org/ver10/error" xmlns:dn="
http://www.onvif.org/ver10/network/wsdl" xmlns:tns1="
http://www.onvif.org/ver10/topics" xmlns:tmd="
http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:wsdl="
http://schemas.xmlsoap.org/wsdl" xmlns:wsoap12="
http://schemas.xmlsoap.org/wsdl/soap12" xmlns:http="
http://schemas.xmlsoap.org/wsdl/http" xmlns:d="
http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsadis="
http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsnt="
http://docs.oasis-open.org/wsn/b-2" xmlns:wsa="
http://www.w3.org/2005/08/addressing" xmlns:wstop="
http://docs.oasis-open.org/wsn/t-1" xmlns:wsrf-bf="
http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsntw="
http://docs.oasis-open.org/wsn/bw-2" xmlns:wsrf-rw="
http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsaw="
http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsrf-r="
http://docs.oasis-open.org/wsrf/r-2" xmlns:trc="
http://www.onvif.org/ver10/recording/wsdl" xmlns:tse="
http://www.onvif.org/ver10/search/wsdl" xmlns:trp="
http://www.onvif.org/ver10/replay/wsdl" xmlns:tnshik="
http://www.hikvision.com/2011/event/topics" xmlns:hikwsd="
http://www.onvifext.com/onvif/ext/ver10/wsdl" xmlns:hikxsd="
http://www.onvifext.com/onvif/ext/ver10/schema" xmlns:tas="
http://www.onvif.org/ver10/advancedsecurity/wsdl" xmlns:tr2="
http://www.onvif.org/ver20/media/wsdl" xmlns:axt="
http://www.onvif.org/ver20/analytics
"><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value>
<env:Subcode><env:Value>ter:ActionNotSupported</env:Value>
<env:Subcode><env:Value>ter:InvalidOperation</env:Value>
</env:Subcode>
</env:Subcode>
</env:Code>
<env:Reason><env:Text xml:lang="en">Optional Action Not
Implemented</env:Text>
</env:Reason>
</env:Fault>
</env:Body>
</env:Envelope>


19:10:38.287: Connection Failed for 192.168.1.37 Port: 80 Username: admin



пт, 14 июл. 2023 г., 22:05 Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
Could you try he test version 2.0.41 as it has a lot of fixes. It looks like the app is try to use the new Media2 interface and that is probably not supported. This was a bug in the ONVIF library which is now fixed.

**Comment by shurick1983** [comment]
Did not help.  Now another error.
![Screenshot_20230715_091845_Homey](https://github.com/AdyRock/com.onvif/assets/131009382/88169497-745e-4fa0-ac6e-eda79a1c5f42)

Message sent: <504fcb7e-1196-cba9-87a6-445c2808d2da@ady.duckdns.org>

**Comment by bartje78** [comment]
Hi! 
Did anyone reached a solution to this? I am facing the same problem (Error: ONVIF SOAP Fault), after removing my camera from Homey app and now trying to re-add it.

**Comment by shurick1983** [comment]
Hi. I still have the same problem, I can't connect my camera through the ONVIF app.  Through other applications using the ONVIF protocol, everything works well.

**Comment by bartje78** [comment]
I’ve managed to get it to work by creating a new user account, and log in with the new username and password; that solved it for me!

**Comment by shurick1983** [comment]
Hi!
I installed the latest version and now a new error: Error: Discovery error:
undefined.  I sent the log.  I see that the time in the log differs from my
real time by 3 hours, is it supposed to be like this?

чт, 17 авг. 2023 г., 19:23 Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
I haven't received the log. Did you send it from app settings page?

The time obtained from Homey is always UTC, so that probably explains the difference.

**Comment by shurick1983** [comment]
Yes, I did it from the app.  Sending screenshots of the problem.

чт, 17 авг. 2023 г., 20:45 Adrian Rockall ***@***.***>:

**Comment by AdyRock** [comment]
If you want to include pictures you have to do it via the GitHub Web interface as it doesn't support attachments.

**Comment by shurick1983** [comment]
![Screenshot_20230817_204903_Homey](https://github.com/AdyRock/com.onvif/assets/131009382/38bebb33-dd4c-4888-a30a-3b60135531c7)
![Screenshot_20230817_204947_Homey](https://github.com/AdyRock/com.onvif/assets/131009382/a065b086-b80a-45af-bb9f-d09517ceff6c)

**Comment by AdyRock** [comment]
Could you select Full Information in the drop list above the log view, and then try again.

**Comment by shurick1983** [comment]
Message sent: ***@***.***>

чт, 17 авг. 2023 г., 21:58 Adrian Rockall ***@***.***>:

**Comment by shurick1983** [comment]
19:8:24.053: Sending log
19:8:40.384: Message sent: <
***@***.***>

чт, 17 авг. 2023 г., 22:04 Александр Ковальчук ***@***.***>:

**Comment by shurick1983** [comment]
<tt:Minor>60</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver10/events/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/Events</tds:XAddr>
<tds:Capabilities><tev:Capabilities WSSubscriptionPolicySupport="true" WSPullPointSupport="true" WSPausableSubscriptionManagerInterfaceSupport="false" MaxNotificationProducers="10" MaxPullPoints="10"></tev:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>2</tt:Major>
<tt:Minor>60</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver20/imaging/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/Imaging</tds:XAddr>
<tds:Capabilities><timg:Capabilities ImageStabilization="false"></timg:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>16</tt:Major>
<tt:Minor>6</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver10/deviceIO/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/DeviceIO</tds:XAddr>
<tds:Capabilities><tmd:Capabilities VideoSources="1" VideoOutputs="0" AudioSources="1" AudioOutputs="1" RelayOutputs="1" DigitalInputs="1" SerialPorts="1" DigitalInputOptions="true"></tmd:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>16</tt:Major>
<tt:Minor>12</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver20/analytics/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/Analytics</tds:XAddr>
<tds:Capabilities><tan:Capabilities RuleSupport="true" AnalyticsModuleSupport="true" RuleOptionsSupported="false" CellBasedSceneDescriptionSupported="true"/>
</tds:Capabilities>
<tds:Version><tt:Major>16</tt:Major>
<tt:Minor>12</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver10/recording/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/Recording</tds:XAddr>
<tds:Capabilities><trc:Capabilities DynamicRecordings="false" DynamicTracks="false" Encoding="G711 G726 H264 JPEG" MaxRate="16384" MaxTotalRate="16384" MaxRecordings="1" MaxRecordingJobs="1" Options="true"></trc:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>16</tt:Major>
<tt:Minor>12</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver10/search/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/SearchRecording</tds:XAddr>
<tds:Capabilities><tse:Capabilities MetadataSearch="false" GeneralStartEvents="false"></tse:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>2</tt:Major>
<tt:Minor>42</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver10/replay/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/Replay</tds:XAddr>
<tds:Capabilities><trp:Capabilities ReversePlayback="false" SessionTimeoutRange="1 60" RTP_RTSP_TCP="true"></trp:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>2</tt:Major>
<tt:Minor>21</tt:Minor>
</tds:Version>
</tds:Service>
<tds:Service><tds:Namespace>http://www.onvif.org/ver20/media/wsdl</tds:Namespace>
<tds:XAddr>http://192.168.1.127/onvif/Media2</tds:XAddr>
<tds:Capabilities><tr2:Capabilities SnapshotUri="true" Rotation="false" VideoSourceMode="true" OSD="true" Mask="true"><tr2:ProfileCapabilities MaximumNumberOfProfiles="10" ConfigurationsSupported="VideoSource VideoEncoder AudioSource AudioEncoder AudioOutput AudioDecoder Metadata Analytics"></tr2:ProfileCapabilities>
<tr2:StreamingCapabilities RTSPStreaming="true" RTPMulticast="true" RTP_RTSP_TCP="true" NonAggregateControl="false"></tr2:StreamingCapabilities>
</tr2:Capabilities>
</tds:Capabilities>
<tds:Version><tt:Major>16</tt:Major>
<tt:Minor>12</tt:Minor>
</tds:Version>
</tds:Service>
</tds:GetServicesResponse>
</env:Body>
</env:Envelope>


19:5:14.526: getServices (192.168.1.127): [
	{
		"getServicesResponse": [
			{
				"service": [
					{
						"namespace": [
							"http://www.onvif.org/ver10/device/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/device_service"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"network": [
											{
												"$": {
													"IPFilter": "true",
													"ZeroConfiguration": "true",
													"IPVersion6": "true",
													"DynDNS": "true",
													"Dot11Configuration": "false",
													"Dot1XConfigurations": "0",
													"HostnameFromDHCP": "true",
													"NTP": "1",
													"DHCPv6": "true"
												}
											}
										],
										"security": [
											{
												"$": {
													"TLS1.0": "true",
													"TLS1.1": "true",
													"TLS1.2": "true",
													"OnboardKeyGeneration": "false",
													"AccessPolicyConfig": "false",
													"DefaultAccessPolicy": "true",
													"Dot1X": "false",
													"RemoteUserHandling": "false",
													"X.509Token": "false",
													"SAMLToken": "false",
													"KerberosToken": "false",
													"UsernameToken": "true",
													"HttpDigest": "true",
													"RELToken": "false",
													"SupportedEAPMethods": "0",
													"MaxUsers": "32",
													"MaxUserNameLength": "32",
													"MaxPasswordLength": "16"
												}
											}
										],
										"system": [
											{
												"$": {
													"DiscoveryResolve": "false",
													"DiscoveryBye": "true",
													"RemoteDiscovery": "false",
													"SystemBackup": "false",
													"SystemLogging": "true",
													"FirmwareUpgrade": "true",
													"HttpFirmwareUpgrade": "true",
													"HttpSystemBackup": "false",
													"HttpSystemLogging": "false",
													"HttpSupportInformation": "false",
													"StorageConfiguration": "true",
													"MaxStorageConfigurations": "8"
												}
											}
										]
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"16"
								],
								"minor": [
									"12"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver10/media/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Media"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"SnapshotUri": "true",
											"Rotation": "false",
											"VideoSourceMode": "true",
											"OSD": "true"
										},
										"profileCapabilities": [
											{
												"$": {
													"MaximumNumberOfProfiles": "10"
												}
											}
										],
										"streamingCapabilities": [
											{
												"$": {
													"RTPMulticast": "true",
													"RTP_TCP": "true",
													"RTP_RTSP_TCP": "true",
													"NonAggregateControl": "false"
												}
											}
										]
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"2"
								],
								"minor": [
									"60"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver10/events/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Events"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"WSSubscriptionPolicySupport": "true",
											"WSPullPointSupport": "true",
											"WSPausableSubscriptionManagerInterfaceSupport": "false",
											"MaxNotificationProducers": "10",
											"MaxPullPoints": "10"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"2"
								],
								"minor": [
									"60"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver20/imaging/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Imaging"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"ImageStabilization": "false"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"16"
								],
								"minor": [
									"6"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver10/deviceIO/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/DeviceIO"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"VideoSources": "1",
											"VideoOutputs": "0",
											"AudioSources": "1",
											"AudioOutputs": "1",
											"RelayOutputs": "1",
											"DigitalInputs": "1",
											"SerialPorts": "1",
											"DigitalInputOptions": "true"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"16"
								],
								"minor": [
									"12"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver20/analytics/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Analytics"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"RuleSupport": "true",
											"AnalyticsModuleSupport": "true",
											"RuleOptionsSupported": "false",
											"CellBasedSceneDescriptionSupported": "true"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"16"
								],
								"minor": [
									"12"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver10/recording/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Recording"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"DynamicRecordings": "false",
											"DynamicTracks": "false",
											"Encoding": "G711 G726 H264 JPEG",
											"MaxRate": "16384",
											"MaxTotalRate": "16384",
											"MaxRecordings": "1",
											"MaxRecordingJobs": "1",
											"Options": "true"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"16"
								],
								"minor": [
									"12"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver10/search/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/SearchRecording"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"MetadataSearch": "false",
											"GeneralStartEvents": "false"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"2"
								],
								"minor": [
									"42"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver10/replay/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Replay"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"ReversePlayback": "false",
											"SessionTimeoutRange": "1 60",
											"RTP_RTSP_TCP": "true"
										}
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"2"
								],
								"minor": [
									"21"
								]
							}
						]
					},
					{
						"namespace": [
							"http://www.onvif.org/ver20/media/wsdl"
						],
						"XAddr": [
							"http://192.168.1.127/onvif/Media2"
						],
						"capabilities": [
							{
								"capabilities": [
									{
										"$": {
											"SnapshotUri": "true",
											"Rotation": "false",
											"VideoSourceMode": "true",
											"OSD": "true",
											"Mask": "true"
										},
										"profileCapabilities": [
											{
												"$": {
													"MaximumNumberOfProfiles": "10",
													"ConfigurationsSupported": "VideoSource VideoEncoder AudioSource AudioEncoder AudioOutput AudioDecoder Metadata Analytics"
												}
											}
										],
										"streamingCapabilities": [
											{
												"$": {
													"RTSPStreaming": "true",
													"RTPMulticast": "true",
													"RTP_RTSP_TCP": "true",
													"NonAggregateControl": "false"
												}
											}
										]
									}
								]
							}
						],
						"version": [
							{
								"major": [
									"16"
								],
								"minor": [
									"12"
								]
							}
						]
					}
				]
			}
		]
	}
]
19:5:14.535: getServices (192.168.1.127): Finished -----
19:5:14.540: callUpstartFunctions (192.168.1.127): Started *****
19:5:14.553: 
_request (192.168.1.127): {
	"hostname": "192.168.1.127",
	"port": 80,
	"agent": false,
	"path": "/onvif/Media2",
	"timeout": 15000,
	"headers": {
		"Content-Type": "application/soap+xml; charset: utf-8; action=\"http://www.onvif.org/ver10/media/wsdl/GetProfiles\"",
		"Content-Length": 1017,
		"charset": "utf-8"
	},
	"method": "POST"
}
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><a:MessageID> urn:uuid:ad7229d4-f1f4-3e4f-d1f0-2e30a16ca819</a:MessageID><Security s:mustUnderstand="1" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>user</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">0CMrRKQo3TNhpfGNMpBzCnwid2w=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">mCadQqfHojmMWKg+UmzhLw==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-08-17T19:05:14.098Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetProfiles xmlns="http://www.onvif.org/ver10/media/wsdl"/></s:Body></s:Envelope>

19:5:14.575: 
_request response (192.168.1.127): <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:soapenc="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tst="http://www.onvif.org/ver10/storage/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12" xmlns:http="http://schemas.xmlsoap.org/wsdl/http" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsntw="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:hikwsd="http://www.onvifext.com/onvif/ext/ver10/wsdl" xmlns:hikxsd="http://www.onvifext.com/onvif/ext/ver10/schema" xmlns:tas="http://www.onvif.org/ver10/advancedsecurity/wsdl" xmlns:tr2="http://www.onvif.org/ver20/media/wsdl" xmlns:axt="http://www.onvif.org/ver20/analytics"><env:Body><tr2:GetProfilesResponse><tr2:Profiles token="Profile_1" fixed="true"><tr2:Name>mainStream</tr2:Name>
<tr2:Configurations></tr2:Configurations>
</tr2:Profiles>
<tr2:Profiles token="Profile_2" fixed="true"><tr2:Name>subStream</tr2:Name>
<tr2:Configurations></tr2:Configurations>
</tr2:Profiles>
</tr2:GetProfilesResponse>
</env:Body>
</env:Envelope>


19:5:14.591: 
_request (192.168.1.127): {
	"hostname": "192.168.1.127",
	"port": 80,
	"agent": false,
	"path": "/onvif/Media2",
	"timeout": 15000,
	"headers": {
		"Content-Type": "application/soap+xml; charset: utf-8; action=\"http://www.onvif.org/ver10/media/wsdl/GetVideoSources\"",
		"Content-Length": 1021,
		"charset": "utf-8"
	},
	"method": "POST"
}
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://www.w3.org/2005/08/addressing"><s:Header><a:MessageID> urn:uuid:33f86db7-6360-160b-256c-67c27c6e1792</a:MessageID><Security s:mustUnderstand="1" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>user</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">hPx7v5cZU5Mi+Ybngp6Di1GsUUg=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">OvMc915gW85RjUSRKvPxyw==</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-08-17T19:05:14.134Z</Created></UsernameToken></Security></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><GetVideoSources xmlns="http://www.onvif.org/ver10/media/wsdl"/></s:Body></s:Envelope>

19:5:14.610: 
_request response (192.168.1.127): <?xml version="1.0" encoding="UTF-8"?>
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:soapenc="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tst="http://www.onvif.org/ver10/storage/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl" xmlns:wsoap12="http://schemas.xmlsoap.org/wsdl/soap12" xmlns:http="http://schemas.xmlsoap.org/wsdl/http" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrf-bf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wsntw="http://docs.oasis-open.org/wsn/bw-2" xmlns:wsrf-rw="http://docs.oasis-open.org/wsrf/rw-2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsrf-r="http://docs.oasis-open.org/wsrf/r-2" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:hikwsd="http://www.onvifext.com/onvif/ext/ver10/wsdl" xmlns:hikxsd="http://www.onvifext.com/onvif/ext/ver10/schema" xmlns:tas="http://www.onvif.org/ver10/advancedsecurity/wsdl" xmlns:tr2="http://www.onvif.org/ver20/media/wsdl" xmlns:axt="http://www.onvif.org/ver20/analytics"><env:Body><env:Fault><env:Code><env:Value>env:Receiver</env:Value>
<env:Subcode><env:Value>ter:ActionNotSupported</env:Value>
<env:Subcode><env:Value>ter:InvalidOperation</env:Value>
</env:Subcode>
</env:Subcode>
</env:Code>
<env:Reason><env:Text xml:lang="en">Optional Action Not Implemented</env:Text>
</env:Reason>
</env:Fault>
</env:Body>
</env:Envelope>



19:5:14.621: Connection Failed for 192.168.1.127 Port: 80 Username: user
19:5:14.633: Failed to connect to camera, errpr: undefined
19:8:24.053: Sending log
19:8:40.384: Message sent: <904e9a25-cf3c-55f4-3059-9ad7d806d393@ady.duckdns.org>

**Comment by shurick1983** [comment]
Hi! Did you manage to find out something about the cause of my problem?

**Comment by AdyRock** [comment]
Sorry, I missed the update with the log.
The error being reported is 'Optional Action Not Implemented' when the app tries to get the video sources.
I think this is only required to support NVR's, so I might be able to cope with not getting it (or trapping the error and continuing).
I am in the process of promisifying the calls, which should allow me to ignore that error, and then I can check the app still works for single cameras without it.

**Comment by AdyRock** [comment]
I have published a new test version. Can you see if that works for you?
